---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-gpfshome-{{ .Values.NameSpace }}
  namespace: {{ .Values.NameSpace }}
spec:
  storageClassName: {{ default "gpfs-csi-dynamic" .Values.PVC.StorageClass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ default "500G" .Values.PVC.Size }}
